services:
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    profiles:
      - observability
    ports:
      - '3000:3000'
      - '4317'
      - '4318'
  postgres:
    image: 'postgres:18.4@sha256:b913fd5699b8bd23fa4b06d72ecdd939fad43b80fb8651bac06caa0e6d135cac'
    environment:
      - 'POSTGRES_DB=peak'
      - 'POSTGRES_PASSWORD=peak_migrator'
      - 'POSTGRES_USER=peak_migrator'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U peak_migrator -d peak']
      interval: 10s
      timeout: 5s
      retries: 5
