services:
  peak-api:
    environment:
      PEAK_REPORT_STORAGE_ENABLED: "false"

  peak-worker:
    environment:
      SPRING_PROFILES_ACTIVE: prod,worker,acceptance
      PEAK_REPORT_STORAGE_ENABLED: "false"
