-- V93 — resolving a platform billing callback to the tenant it belongs to.
--
-- A provider callback arrives on a public route carrying no session and no
-- tenant. Everything it needs to be applied against -- the attempt, the purchase
-- -- sits behind row-level security keyed on current_tenant_id(), which is null
-- at that point. So the callback cannot read its own attempt to find out whose
-- it is: a chicken-and-egg that RLS creates by design.
--
-- The same shape as resolve_payment_webhook_scope (V30), which solves it for a
-- property's guest payments. This is the equivalent for Peak's own revenue, and
-- the two must stay separate: that one is keyed on a tenant's provider account,
-- this one on an internal reference Peak minted.
--
-- The lookup is by internal_reference, which is UNIQUE and generated by Peak, so
-- a caller cannot enumerate other tenants by guessing: they would have to know a
-- reference, and knowing one only yields the tenant it already belongs to.

-- -----------------------------------------------------------------------------
-- A dedicated owner. A SECURITY DEFINER function owned by the superuser runs
-- with BYPASSRLS, which DefinerSearchPathIntegrationTests rejects, and rightly:
-- a bug in the body would then see every tenant's rows.
-- -----------------------------------------------------------------------------
DO $migration$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pms_platform_billing_scope_owner') THEN
        CREATE ROLE pms_platform_billing_scope_owner
            NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
    ELSE
        ALTER ROLE pms_platform_billing_scope_owner
            NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
    END IF;
END;
$migration$;

GRANT SELECT ON peak_payment_attempts TO pms_platform_billing_scope_owner;
GRANT SELECT ON peak_purchases TO pms_platform_billing_scope_owner;

-- The owner is NOBYPASSRLS, so without these it would see nothing on an unbound
-- session and every callback would resolve to no tenant -- which reads exactly
-- like an unknown reference. Read-only, scoped to a NOLOGIN role nothing else
-- runs as, and conferring no write reach.
CREATE POLICY platform_billing_scope_owner_reads_attempts ON peak_payment_attempts
    FOR SELECT
    TO pms_platform_billing_scope_owner
    USING (true);

CREATE POLICY platform_billing_scope_owner_reads_purchases ON peak_purchases
    FOR SELECT
    TO pms_platform_billing_scope_owner
    USING (true);

CREATE OR REPLACE FUNCTION resolve_platform_billing_scope(
    p_internal_reference text
) RETURNS TABLE (
    tenant_id uuid,
    attempt_id uuid,
    purchase_id uuid,
    attempt_status text,
    purchase_status text,
    expected_amount numeric,
    expected_currency text,
    provider text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
    SELECT attempt.tenant_id,
           attempt.id,
           attempt.purchase_id,
           attempt.status::text,
           purchase.status::text,
           attempt.amount,
           attempt.currency::text,
           attempt.provider::text
    FROM peak_payment_attempts attempt
    JOIN peak_purchases purchase ON purchase.id = attempt.purchase_id
    WHERE attempt.internal_reference = p_internal_reference;
$$;

ALTER FUNCTION resolve_platform_billing_scope(text)
    OWNER TO pms_platform_billing_scope_owner;

REVOKE ALL ON FUNCTION resolve_platform_billing_scope(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION resolve_platform_billing_scope(text) TO pms_app;
GRANT EXECUTE ON FUNCTION resolve_platform_billing_scope(text) TO pms_worker;

-- The callback ledger is written on a session that has just been bound to the
-- tenant the scope lookup returned, so the ordinary tenant policy covers it. But
-- the row must be insertable before the attempt is confirmed, including when the
-- signature failed -- a rejected callback is evidence and must be recorded.
GRANT SELECT, INSERT, UPDATE ON peak_provider_events TO pms_app, pms_worker;

DO $migration$
DECLARE
    missing text;
BEGIN
    SELECT string_agg(expected.name, ', ')
    INTO missing
    FROM (VALUES ('resolve_platform_billing_scope')) AS expected(name)
    WHERE NOT EXISTS (
        SELECT 1 FROM pg_proc WHERE proname = expected.name
    );

    IF missing IS NOT NULL THEN
        RAISE EXCEPTION 'V93 did not create: %', missing;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pg_proc proc
        JOIN pg_roles owner ON owner.oid = proc.proowner
        WHERE proc.proname = 'resolve_platform_billing_scope'
          AND (owner.rolsuper OR owner.rolbypassrls)
    ) THEN
        RAISE EXCEPTION
            'resolve_platform_billing_scope must not be owned by a superuser or a BYPASSRLS role';
    END IF;
END;
$migration$;
